### ISSUE TITLE
[문의] pro 버전의 업데이트도 예정되어 있나요?

### ISSUE THREAD

**Issue by roeniss** [Dalgona/neodgm-pro#1]
https://github.com/Dalgona/neodgm/releases/tag/v1.520 와 마찬가지로, pro 버전에서도 버전 업데이트가 진행되는지 알고 싶습니다.

**Comment by Dalgona** [comment]
네. 가까운 시일 내에 Neo둥근모 Pro v1.010 업데이트를 공개할 계획입니다.

이 프로젝트는 제 여가 시간을 활용하여 진행하는 만큼, 어느정도 개발에 지연이 있을 수 있습니다. 이 점 양해 부탁드립니다. 🙇‍♂️

**Comment by roeniss** [comment]
@Dalgona 양해라뇨, 당연히 기다려야죠. 여담으로 (모르실 것 같지는 않지만 혹시나 하고...) Buy me a Coffee 같은 링크를 열어두는게 좋지 않을까 하는 생각이 들었습니다. 요즘엔 깃헙 자체에서도 제공하고요.

**Comment by Dalgona** [comment]
🎉 Neo둥근모 Pro의 새 버전 v1.010이 릴리즈 되었습니다. [[릴리즈 노트]](https://github.com/Dalgona/neodgm-pro/releases/tag/v1.010)
