### ISSUE TITLE
맥북에서 서체 설치 시 preview가 이상하게 표시됨

### ISSUE THREAD

**Issue by roeniss** [Dalgona/neodgm-pro#2]
![image](https://user-images.githubusercontent.com/26613280/115979425-d9b8c180-a5c0-11eb-880d-1b293ec059e9.png)

사용엔 지장이 없지만, 설치할 때 이렇게 나오는 부분 제보 드립니다

**Comment by roeniss** [comment]
(지금 스크린샷 보고 알았는데) 설치 된 상태인데 좌측 하단에 "(설치되지 않음)"이라고 뜨는 버그도 있네요. 
마찬가지로, 사용하는데 지장은 없습니다.

**Comment by Dalgona** [comment]
글꼴 미리보기 화면에서 [?]로 표시되는 부분은 한자, 가나 문자 등등 현재 Neo둥근모 Pro에서 지원하지 않는 글자들이므로, 이는 정상입니다. 앞으로도 더 많은 문자들을 지원할 계획이 있지만, 한자가 추가될 가능성은 낮을 것 같습니다.

"(설치되지 않음)"이라고 표시되는 문제는 제 환경에서도 발생하는 문제긴 한데, 이건 제가 어떻게 할 수 있는 게 아닌 것 같아요. 😂

**Comment by Dalgona** [comment]
글꼴 파일에 저 미리보기 화면에 표시될 텍스트 데이터를 별도로 추가할 수도 있지만, 아직 적절한 문장이 정해지지 않았고, macOS 이외의 OS에서는 이 데이터를 인식하지 않아서 공식적으로 적용하지는 않았습니다.

<img width="854" alt="스크린샷 2021-04-25 오후 12 31 57" src="https://user-images.githubusercontent.com/2667858/115979700-4ed8c680-a5c2-11eb-8afe-8202a7b966a4.png">
